name: Download build artifact
run-name: ${{ github.actor }} is downloading a build artifact
on:
  workflow_run:
    workflows: ["Create build artifact"]
    types:
      - completed
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
          run-id: ${{ github.event.workflow_run.id }}
