name: Create build artifact
run-name: ${{ github.actor }} is creating a build artifact
on: [push]
jobs:
  example-job:
    name: Save output
    runs-on: ubuntu-latest
    steps:
      - run: "echo github.env:  ${{github.env}}"
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log

